name: Deploy Main App

on:
  push:
    branches: [ "main" ]

jobs:
  call-acr-template:
    uses: karolarcemz-crypto/templates-workflows/.github/workflows/Azure-ACR.yml@main
    with:
      java-version: '17'
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
