name: Deploy Main App

on:
  push:
    branches: [ "main" ]

jobs:
  call-acr-template:
    uses: karolarcemz-crypto/templates-workflows/.github/workflows/Azure-ACR.yml@main
    with:
      java-version: '17' # Opcional
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.DOCKERHUB_USERNAME }}
      ACR_USERNAME: ${{ secrets.DOCKER_CREDS_USR }}
      ACR_PASSWORD: ${{ secrets.DOCKER_CREDS_PSW }}
